#!/bin/bash
echo "Trying to find Flower care bluetooth devices to add..."
#toggle the bluetooth device
hciconfig hci0 down
hciconfig hci0 up
#lescan continues to scan until it is stopped, so we will fork it's process,
#let it run for a while, then kill it.
#output hcitool lescan's buffer to a txt file, and put it in the background
hcitool lescan > bluetooth_devices.txt &
pid=$!
#wait 10 seconds before killing the process
sleep 10s
kill -INT $pid
wait $pid
num=0
#make sure we don't have the same sensor names that are already added to the config file
while grep "Flora-care$num" /opt/miflora-mqtt-daemon/config.ini > /dev/null;
do
  ((num++))
done
#make sure we don't already have the MAC address of the sensor before adding it to the config file
cat bluetooth_devices.txt | grep -w "Flower care"| cut -c-17 | while read line
do
  sensor="Flora-care$num = $line"
  if grep -q "$line" /opt/miflora-mqtt-daemon/config.ini; then
    #the mac address of the sensor is already in
    echo "$line is already in the config.ini"
  else
    #append the config.ini file with the new mac address
    sudo echo $sensor >> /opt/miflora-mqtt-daemon/config.ini
    ((num++))
  fi
done
sudo rm -f bluetooth_devices.txt
