#!/bin/bash
echo "Trying to find Flower care bluetooth devices to add..."
#toggle the bluetooth device
hciconfig hci0 down
hciconfig hci0 up
#lescan continues to scan until it is stopped, so we will fork it's process,
#let it run for a while, then kill it.
#output hcitool lescan's buffer to a txt file, and put it in the background
hcitool lescan > bluetooth_devices.txt &
pid=$!
#wait 10 seconds before killing the process
sleep 10s
kill -INT $pid
wait $pid

sensors=$(mongo DB_NAME_HERE --eval 'db.Sensors.find()')
#make sure we don't already have the MAC address of the sensor before adding it to the config file
cat bluetooth_devices.txt | grep -w "Flower care"| cut -c-17 | while read line
do
  skip=false
  for address in sensors
  do

    if ["$address" = "$line"]; then
      skip=true
    fi
  done
  if ["$skip" = true]; then
    #the mac address of the sensor is already in
    echo "$line is already in the config.ini"
  else
    #add the new mac address to the db
    mongo DB_NAME_HERE --eval 'db.Sensors.insert({mac:$line})'
  fi
done

sudo rm -f bluetooth_devices.txt
