#!/bin/bash

#make sure services are not running
echo "Stopping netowrk services (if running)..."
systemctl stop hostapd.service
systemctl stop dnsmasq.service
systemctl stop dhcpcd.service


#make sure no uap0 interface exists (may cause error notice)
echo "Removing uap0 interface"
iw dev uap0 del

#add uap0 interface
echo "Adding uap0 interface..."
iw dev wlan0 interface add uap0 type __ap

#modify iptables
echo "IPV4 forwarding setting..."
sysctl net.ipv4.ip_forward=1
echo "Editing IP tables..."
iptables -t nat -A POSTROUTING -s 11.11.11.0/24 ! -d 11.11.11.0/24 -j MASQUERADE

#bring up uap0 interface
ifconfig uap0 up

#start hostapd
echo "Starting hostapd service..."
systemctl start hostapd.service
sleep 10

#start dhcpcd
echo "Starting dhcpcd service..."
systemctl start dhcpcd.service
sleep 5

echo "Starting dnsmasq service..."
systemctl start dnsmasq.service
echo "wifistart DONE"
